version: '3.3'

services:
  db:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:5.6.0
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${HOST_URL}');
        define('WP_SITEURL', '${HOST_URL}');

  wpcli:
    image: wordpress:cli-2.4.0
    depends_on:
      - wordpress
    volumes_from:
      - wordpress
    user: xfs
    command: >
      /bin/sh -c '
      sleep 45;
      wp core install --path="/var/www/html" --url=${HOST_URL} --title=${HOST_TITLE} --admin_user=${ADMIN_USER} --admin_password=${ADMIN_PASSWORD} --admin_email=${ADMIN_EMAIL}
      '

volumes:
  db_data:
