#!/bin/bash

# Unpack tar
sudo tar xzf /tmp/app.tar.gz -C /

# Create log files
sudo mkdir -p /var/log/charlotte-website/ && sudo touch /var/log/charlotte-website/backup.log

# Update permissions
sudo chmod 755 /usr/libexec/charlotte-website/charlotte-website
sudo chmod 755 /usr/local/bin/wordpress-backup
sudo chmod 755 /usr/local/bin/wordpress-restore
sudo chmod 755 /etc/init.d/charlotte-website
sudo chmod 666 /var/log/charlotte-website/backup.log

# Update owners
sudo chown root:root /etc/init.d/charlotte-website 

# Add the service
sudo update-rc.d charlotte-website defaults
sudo update-rc.d charlotte-website enable