#!/bin/bash

# Unpack tar
cp /tmp/app.tar.gz /
tar xzf app.tar.gz
rm -f app.tar.gz

# Update permissions
sudo chmod 755 /usr/local/bin/wordpress-backup
sudo chmod 755 /usr/local/bin/wordpress-restore
