#!/bin/bash

# Unpack tar
sudo tar xzf /tmp/app.tar.gz -C /


# Update permissions
sudo chmod 755 /usr/local/bin/wordpress-backup
sudo chmod 755 /usr/local/bin/wordpress-restore

# Add the service
sudo chmod 755 /etc/init.d/charlotte-website 
sudo chown root:root /etc/init.d/charlotte-website 

sudo update-rc.d charlotte-website defaults
sudo update-rc.d charlotte-website enable