#!/bin/bash
# description: charlotte-website
# processname: charlotte-website

source /etc/init.d/functions


 start() {
    echo -n "Starting charlotte-website: "
    # sudo touch /startupscriptworking.txt
    echo
}

stop() {
    echo -n "Stopping charlotte-website: "
    echo
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
