#!/bin/bash
### BEGIN INIT INFO
# Provides:          charlotte-website
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: charlotte-website
# Description:       charlotte-website
### END INIT INFO


source /etc/init.d/functions


 start() {
    echo -n "Starting charlotte-website: "

    cd /srv/charlotte-website/ && sudo docker-compose up -d

    (. /srv/charlotte-website/.env.export && /usr/libexec/charlotte-website/charlotte-website restore)
    
    sudo rm -f /etc/nginx/sites-enabled/default
    
    sudo service nginx reload

    sudo /usr/local/bin/certs-install

    echo
}

stop() {
    echo -n "Stopping charlotte-website: "

    cd /srv/charlotte-website/ && sudo docker-compose stop
    
    echo
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
