version: '3.3'

services:
  db:
    container_name: ${APP_NAME}-mariadb
    image: mariadb:10.5.8
    command: --lower_case_table_names=2
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  wordpress:
    container_name: ${APP_NAME}-wordpress
    image: wordpress:5.7.1
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/wp-config.php:/var/www/html/wp-config.php
      - ./config/env:/var/www/html/env
      - ./web/plugins:/var/www/html/wp-content/plugins
      - ./web/themes:/var/www/html/wp-content/themes
      - ./web/uploads:/var/www/html/wp-content/uploads
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      WORDPRESS_ENV: ${WP_ENV}
      WORDPRESS_HOME: ${WP_HOME}
      WORDPRESS_SITEURL: ${WP_SITEURL}
      WORDPRESS_AUTH_KEY: ${AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${NONCE_SALT}

volumes:
  wp_data:
  db_data:
