steps:
  - name: "gcr.io/$PROJECT_ID/charlotte-website-build"
    args:
      [
        "make",
        "-s",
        "ENV=${_ENV}",
        "DB_NAME=${_DB_NAME}",
        "DB_ROOT_PASSWORD=${_DB_ROOT_PASSWORD}",
        "WP_HOME=${_WP_HOME}",
        "WP_TABLE_PREFIX=${_WP_TABLE_PREFIX}",
        "AUTH_KEY=${_AUTH_KEY}",
        "SECURE_AUTH_KEY=${_SECURE_AUTH_KEY}",
        "LOGGED_IN_KEY=${_LOGGED_IN_KEY}",
        "NONCE_KEY=${_NONCE_KEY}",
        "AUTH_SALT=${_AUTH_SALT}",
        "SECURE_AUTH_SALT=${_SECURE_AUTH_SALT}",
        "LOGGED_IN_SALT=${_LOGGED_IN_SALT}",
        "NONCE_SALT=${_NONCE_SALT}",
      ]

  - name: "gcr.io/$PROJECT_ID/packer"
    args:
      - build
      - -var
      - project_id=$PROJECT_ID
      - -var
      - machine_type=e2-micro
      - -var
      - image_family=ubuntu-1604-lts
      - -var
      - region=us-east1
      - -var
      - zone=us-east1-b
      - ./deploy/packer.json

  # - name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "compute"
  #     - "instance-groups"
  #     - "managed"
  #     - "rolling-action"
  #     - "replace"
  #     - "charlotte-website-mig-disabled"
  #     - "--max-unavailable=100%"
  #     - "--zone=us-east1-b"

images:
  - "gcr.io/$PROJECT_ID/charlotte-website-build"
