#!/bin/bash

function backup() {
  sudo /usr/local/bin/wordpress-backup -d $DB_NAME -p $DB_ROOT_PASSWORD >>/var/log/charlotte-website/backup.log 2>&1
}

function restore() {
  sudo /usr/local/bin/wordpress-restore -d $DB_NAME -p $DB_ROOT_PASSWORD >>/var/log/charlotte-website/backup.log 2>&1
}


case "$1" in
  backup)
    backup
    ;;
  restore)
    restore
    ;;
  *)
    echo "Usage: $0 {backup|restore}"
    exit 1
esac
